spring:
  application:
    name: student-service
  config:
    import: optional:configserver:http://localhost:8088
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/enrollment
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true